version: '3.8'

services:
  # Database - using different port
  postgres:
    image: postgres:15-alpine
    container_name: calldocker_postgres_manual
    environment:
      POSTGRES_DB: calldocker
      POSTGRES_USER: calldocker
      POSTGRES_PASSWORD: calldocker_dev
    ports:
      - "5433:5432"  # Changed from 5432 to 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  # Redis - using different port
  redis:
    image: redis:7-alpine
    container_name: calldocker_redis_manual
    ports:
      - "6380:6379"  # Changed from 6379 to 6380
    volumes:
      - redis_data:/data

  # MinIO - using different ports
  minio:
    image: minio/minio:latest
    container_name: calldocker_minio_manual
    environment:
      MINIO_ROOT_USER: calldocker
      MINIO_ROOT_PASSWORD: calldocker_dev
    ports:
      - "9002:9000"  # Changed from 9000 to 9002
      - "9003:9001"  # Changed from 9001 to 9003
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  postgres_data:
  redis_data:
  minio_data:

