services:
  - type: web
    name: calldocker-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
    healthCheckPath: /health

  - type: pserv
    name: calldocker-db
    env: postgresql
    plan: free
    databaseName: calldocker
    databaseUser: calldocker_user
